version: '3.4'
services:
  traefik:
    image: traefik:2.1
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
    - /etc/traefik:/etc/traefik
    - /var/run/docker.sock:/var/run/docker.sock:ro
  api:
    image: micado/eec:0.7
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.my-app.rule=Host(`example.com`)'
      - 'traefik.http.routers.my-app.tls=true'
      - 'traefik.http.routers.my-app.tls.certresolver=lets-encrypt'
    hostname: eec
    ports:
      - 5000:5000
    environment:
      MICADO_CLI_DIR: /etc/micado
      MICADO_VERS: v0.10.0
      MASTER_SPEC: /etc/eec/micado_spec.yaml
    volumes:
      - /etc/micado:/etc/micado
      - /etc/eec:/etc/eec
